extends "res://tests/test_case.gd"

const ITEMS := preload("res://autoload/item_db.gd")
const INVENTORY := preload("res://autoload/inventory.gd")
const EQUIPMENT := preload("res://scripts/player/player_equipment.gd")
const PLAYER := preload("res://autoload/player_state.gd")
const CHARACTER := preload("res://scripts/save/character_save.gd")
const WORLD := preload("res://scripts/save/world_save.gd")
const SAVE := preload("res://scripts/save/save_game.gd")

func test_equip_swap_and_unequip_conserve_real_items_in_a_full_bag() -> void:
	var db := ITEMS.new()
	var bag := INVENTORY.new(db)
	var gear := EQUIPMENT.new()
	gear.configure(db)
	bag.add("hide_vest", 1)
	assert_true(gear.equip_from_inventory("hide_vest", bag))
	assert_eq(bag.count("hide_vest"), 0)
	bag.add("insulated_vest", 1)
	for index in range(1, bag.slot_count()):
		bag.set_slot(index, {"id": "wood", "n": 1})
	assert_true(bag.is_full())
	assert_true(gear.equip_from_inventory("insulated_vest", bag))
	assert_eq(gear.equipped_in("upper_body"), "insulated_vest")
	assert_eq(bag.count("insulated_vest"), 0)
	assert_eq(bag.count("hide_vest"), 1)
	var revision := bag.revision
	assert_false(gear.unequip_to_inventory("upper_body", bag))
	assert_eq(bag.revision, revision)
	assert_eq(gear.equipped_in("upper_body"), "insulated_vest")
	bag.remove("wood", 1)
	assert_true(gear.unequip_to_inventory("upper_body", bag))
	assert_eq(gear.equipped_in("upper_body"), "")
	assert_eq(bag.count("insulated_vest"), 1)

func test_invalid_or_missing_carried_item_cannot_create_equipment() -> void:
	var db := ITEMS.new()
	var bag := INVENTORY.new(db)
	var gear := EQUIPMENT.new()
	gear.configure(db)
	bag.add("wood", 2)
	assert_false(gear.equip_from_inventory("wood", bag))
	assert_false(gear.equip_from_inventory("insulated_helm", bag))
	assert_eq(bag.count("wood"), 2)
	assert_eq(gear.equipped_in("helmet"), "")

func test_portable_character_roundtrip_preserves_worn_gear_separately() -> void:
	var db := ITEMS.new()
	var player := PLAYER.new()
	player.configure(db)
	player.inventory.add("insulated_boots", 1)
	assert_true(player.equipment.equip_from_inventory("insulated_boots", player.inventory))
	var data := player.save_data()
	var flat := data.duplicate(true)
	flat["current_realm"] = data.realm
	var partition := CHARACTER.partition(flat)
	assert_true(partition.has("equipment"))
	assert_false(WORLD.partition(flat).has("equipment"))
	var merged := CHARACTER.merge(WORLD.partition(flat), partition, SAVE.VERSION)
	assert_eq(merged.equipment.boots, "insulated_boots")
	var other := PLAYER.new()
	other.configure(db)
	other.load_data(data)
	assert_eq(other.equipment.equipped_in("boots"), "insulated_boots")
	assert_eq(other.inventory.count("insulated_boots"), 0)
	assert_true(other.equipment.unequip_to_inventory("boots", other.inventory))
	assert_eq(other.inventory.count("insulated_boots"), 1)

func test_legacy_and_malformed_equipment_reset_without_cross_slot_items() -> void:
	var gear := EQUIPMENT.new()
	gear.configure(ITEMS.new())
	gear.equip("hide_helm")
	gear.load_data({"helmet": "insulated_boots", "boots": "insulated_boots", "backpack": 7, "weapon": "hide_vest"})
	assert_eq(gear.equipped_in("helmet"), "")
	assert_eq(gear.equipped_in("boots"), "insulated_boots")
	assert_eq(gear.equipped_in("backpack"), "")
	gear.load_data({})
	assert_eq(gear.equipped_in("boots"), "")
	gear.load_data(["hide_helm"])
	assert_eq(gear.equipped_in("helmet"), "")

func test_flat_v23_migration_preserves_inventory_and_clears_legacy_gear() -> void:
	var saver := SAVE.new("user://equipment_migration/")
	var old := {"version": 23, "inventory": [{"id": "insulated_vest", "n": 1}]}
	var migrated: Dictionary = saver.call("_migrate_to_current", old, 23, 1)
	assert_eq(migrated.version, SAVE.VERSION)
	assert_eq(migrated.equipment, {})
	assert_eq(migrated.inventory, old.inventory)
	assert_false(old.has("equipment"), "migration must not mutate source payload")
	var player := PLAYER.new()
	player.configure(ITEMS.new())
	player.equipment.equip("hide_helm")
	player.load_data(migrated)
	assert_eq(player.equipment.equipped_in("helmet"), "")
	assert_eq(player.inventory.count("insulated_vest"), 1)
