extends RefCounted

## Freshness guard for the `data/terrain/playground` bake, the same shape as
## `scripts/world/scatter_bake.gd`'s `config_fingerprint()`/`is_fresh()` pair
## for the OTHER offline bake `build_playground_terrain.gd` produces.
##
## `build_playground_terrain.gd` reads exactly one data input --
## `data/config/terrain_playground.json` (via `playground_heightfield.gd::
## load_config()`) -- to produce the committed `.res` region files under
## `data/terrain/playground/`. Nothing else on disk feeds that bake: no band
## files, no second config, unlike the scatter bake this mirrors. This file
## is the only thing that reads or writes `data/terrain/<world_name>/
## manifest.json`; `build_playground_terrain.gd` is the only thing that
## calls `write_manifest`.
##
## HARNESS-HYGIENE-0903: added after `terrain_playground.json` was edited
## (doc-path text in comments, during the 2026-09-02 repository reset) with
## no re-bake, and nothing on disk or in CI could tell. `data/scatter/
## playground` already had exactly this guard; `data/terrain/playground` had
## none.

const CONFIG_PATH := "res://data/config/terrain_playground.json"


## Hash of the one file this bake depends on. Whole raw text, not a parsed
## subset -- matching `scatter_bake.gd::config_fingerprint()`'s own choice,
## any byte change (including a comment) is a real edit to the file the bake
## reads and has to be able to invalidate a bake, not just a schema change.
static func config_fingerprint() -> int:
	var file := FileAccess.open(CONFIG_PATH, FileAccess.READ)
	if file == null:
		return 0
	var mixed := file.get_as_text().hash() + int(CONFIG_PATH.hash())
	# Masked to 53 bits for the same reason `scatter_bake.gd` masks its own
	# fingerprint: this number is written into manifest.json and read back
	# through `JSON.parse_string`, which has no integer type -- every number
	# comes back as a double, and doubles stop representing consecutive
	# integers exactly past 2^53. See that file's own comment for the
	# concrete failure this avoids.
	return mixed & 0x1FFFFFFFFFFFFF


static func manifest_path(data_dir: String) -> String:
	return "%s/manifest.json" % data_dir


static func read_manifest(data_dir: String) -> Dictionary:
	var file := FileAccess.open(manifest_path(data_dir), FileAccess.READ)
	if file == null:
		return {}
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	return parsed if parsed is Dictionary else {}


## True only when `data_dir` holds a manifest stamped from the EXACT config
## this call site is about to use. False for "no bake yet" and for "bake is
## stale" alike, same as `scatter_bake.gd::is_fresh()` -- both mean "the
## committed data cannot be trusted to match the live config," and the
## caller does not need to tell them apart.
static func is_terrain_bake_fresh(data_dir: String = "res://data/terrain/playground") -> bool:
	var manifest := read_manifest(data_dir)
	if manifest.is_empty():
		return false
	return int(manifest.get("config_fingerprint", 0)) == config_fingerprint()


## Stamp `data_dir/manifest.json` with the fingerprint of the config that
## just produced it. Called only after a FULL bake (every region in the
## configured world bounds) -- `build_playground_terrain.gd` also supports
## baking an explicit `--regions=` subset for the bit-identity test, and a
## partial run must never stamp the whole world fresh, so it skips this call
## entirely rather than being told to leave it out here.
static func write_manifest(data_dir: String, region_count: int) -> void:
	var absolute := ProjectSettings.globalize_path(data_dir)
	if not DirAccess.dir_exists_absolute(absolute):
		DirAccess.make_dir_recursive_absolute(absolute)
	var manifest := {
		"config_fingerprint": config_fingerprint(),
		"regions": region_count,
		"_comment": "Generated by scripts/world/build_playground_terrain.gd (full bake only). Do not hand-edit -- re-run the bake after any change to data/config/terrain_playground.json.",
	}
	var manifest_file := FileAccess.open(manifest_path(data_dir), FileAccess.WRITE)
	manifest_file.store_string(JSON.stringify(manifest, "  "))
	manifest_file = null
