const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert'); const root=process.cwd();const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const out='ralph/reports/TRAINING/f28';fs.mkdirSync(out,{recursive:true});
const m=read('data/config/masters.json'), f=read('data/recipes/feasts.json'), core=read('data/items/items.json').items, water=read('data/config/water_crafting.json').item_registration_proposals;
const known={...core,...water,...f.items};const failures=[];let checks=0;function check(ok,msg){checks++;if(!ok)failures.push(msg)}
check(m.masters.length===5,'five masters');check(JSON.stringify(m.masters.map(x=>x.cap_level))==='[10,20,30,40,50]','live cap order');check(m.ceiling===60&&JSON.stringify(m.reserved_caps)==='[70,80,90,100]','ceiling and reserved data');check(new Set(m.masters.map(x=>x.humanoid_key)).size===5,'five installed cast identities');check(new Set(m.masters.map(x=>x.combat.pattern_id)).size===5,'distinct combat questions');const a=read('data/config/art.json');for(const r of m.masters){check(!!a[r.humanoid_key],'cast config '+r.id);check(fs.existsSync(r.scene.replace('res://','')),'scene '+r.id);check(r.participants===1&&r.combat.no_switch&&r.combat.no_flee&&!r.combat.trainer_damage&&!r.combat.catchable,'one-creature duel rules '+r.id)}
const sourceFiles=['data/config/bands/band1_lower_meadows/harvest.json','data/config/bands/band2_stone_and_root/harvest.json','data/config/bands/band4_upper_meadows_ironwood/harvest.json','data/config/water_pickups.json','data/config/cloudreach_chapter.json','data/config/stormwood_harvests.json','data/config/burrow_warrens.json','data/recipes/feasts.json'];const sources={};
function scan(o,p,file,biome){if(!o||typeof o!=='object')return;if(!Array.isArray(o)){const item=o.item||o.item_id||o.resource_id;if(typeof item==='string'&&(o.at||o.position||o.offset||o.chamber)) (sources[item]??=[]).push({file,json_path:p,biome,stable_id:o.id||o.order||o.flag||'',position:o.at||o.position||o.offset||[],amount:o.amount||o.yield||1,status:file.endsWith('feasts.json')?'owned_source_requires_typed_host_mount':'existing_authored_source_no_runtime_reproof'});}for(const [k,v]of Object.entries(o)){if(k.startsWith('_'))continue;scan(v,p+'.'+k,file,biome)}}
for(const file of sourceFiles){const biome=file.includes('water')?'tidewake':file.includes('cloudreach')?'cloudreach':file.includes('stormwood')?'stormwood':'meadows';scan(read(file),'$',file,biome)}
sources.sunstone=[{file:'scripts/world/playground_world.gd',symbol:'SUNSTONE_AT / _spawn_sunstone',position:[121,7336],biome:'meadows',status:'existing_optional_stone_pickup_no_runtime_reproof'}];
const order=read('data/config/biome_order.json').live;const ledger=[];for(const [id,r]of Object.entries(f.recipes)){check(r.station_id==='kitchen'&&r.homestead_only&&r.station_tier===Math.max(1,r.tier-1),'Kitchen tier '+id);check(r.output[id]===1&&Object.keys(r.output).length===1,'one typed output '+id);check(f.items[id].attuned_type===r.attuned_type&&f.items[id].catalyst===r.catalyst,'immutable type/catalyst '+id);check(r.cost['attuned_'+r.attuned_type]===1,'exactly one matching ingredient '+id);const entries=[];for(const [item,n]of Object.entries(r.cost)){check(!!known[item]&&Number.isInteger(n)&&n>0,'catalogue ingredient '+id+'/'+item);const eligible=(sources[item]||[]).filter(x=>order.indexOf(x.biome)>=0&&order.indexOf(x.biome)<=order.indexOf(r.biome));check(eligible.length>0,'reachable ingredient '+id+'/'+item);entries.push({item,count:n,catalogue:core[item]?'data/items/items.json':water[item]?'data/config/water_crafting.json':'data/recipes/feasts.json',source:eligible[0]||null});}ledger.push({recipe_id:id,biome:r.biome,breaks_level:r.tier*10,catalyst_optional:!!r.catalyst,ingredients:entries})}
for(const type of ['ground','water','air','electric','fire','dark','ice','psychic']) check(f.attuned_sources.nodes.filter(x=>x.item==='attuned_'+type).reduce((a,b)=>a+b.amount,0)>=25,'personal five-creature/five-feast supply '+type);
fs.writeFileSync(out+'/ingredient-ledger.json',JSON.stringify({status:'SOURCE_CANDIDATE_ONLY',claim:'All recipe inputs have canonical/owned definitions and authored sources in or before recipe biome. New personal herb sources and Kitchen host producer must mount before runtime acceptance.',biome_order:order,recipes:ledger},null,2)+'\n');
fs.writeFileSync(out+'/source-risk-check.json',JSON.stringify({checks,failures,scope:'Authored JSON identity/catalogue/source/order checks only; no GDScript parse, engine, persistence or acceptance proof.'},null,2)+'\n');console.log(JSON.stringify({checks,failures}));if(failures.length)process.exitCode=1;
