extends SceneTree

## Writes `default_bus_layout.tres` -- the game's mixer, six buses.
##
##   godot --headless --path . --script tools/audio/make_bus_layout.gd
##
## Generated by Godot rather than hand-written as a .tres, for the same reason
## `tools/audio/synth.py` writes a `smpl` chunk instead of forging a `.import`
## sidecar: a resource format is the engine's business, and a hand-typed one is
## correct only until the day it silently is not. Run this again if the bus set
## changes; it is not part of any build, and its output is committed.
##
## ## The bus set
##
## Master
##  |- Music      every score cue
##  |- Ambience   the looping per-region layer beds
##  |- SFX        world verbs, combat impacts, everything one-shot and physical
##  |- Creatures  creature vocalisations, kept off SFX so the player can turn
##  |             down "the animals are noisy" without also turning down their
##  |             own footsteps -- these are the two most likely complaints and
##  |             they have opposite fixes
##  '- UI         menu blips; `scripts/ui/audio_cues.gd` moves onto this
##
## Five children rather than the more usual three (music/sfx/ui) because the
## settings screen exposes one slider per bus, and "Ambience" and "Creatures"
## are exactly the two the target player is most likely to want independently:
## a long exploration chapter with a wind bed under all of it, and a game whose
## creatures are meant to be constantly audible.
##
## No effects are attached. A compressor on Master is the obvious next thing and
## is deliberately NOT here yet: this lane's job is to make the game audible at
## all, and an unmeasured compressor is how a mix gets quietly worse while
## looking more professional in the editor.

const OUT_PATH := "res://default_bus_layout.tres"

## Bus name -> volume in dB at its shipped default. These are the MIX, and they
## are the one set of audio numbers that cannot live in `data/config/audio.json`
## -- the layout is a resource the engine loads before any config reader runs.
## Per-player volume is a multiplier on top of these, set by the settings screen.
##
## Ambience sits low on purpose. It plays continuously for hours, and the
## failure mode nobody reports but everybody feels is an ambience bed mixed at
## the same level as the events it is supposed to sit behind.
const BUSES := {
	"Music": -8.0,
	"Ambience": -12.0,
	"SFX": -4.0,
	"Creatures": -5.0,
	"UI": -6.0,
}


func _init() -> void:
	# Bus 0 is Master and always exists; everything else is added under it.
	AudioServer.set_bus_count(1 + BUSES.size())
	var index := 1
	for name: String in BUSES.keys():
		AudioServer.set_bus_name(index, name)
		AudioServer.set_bus_volume_db(index, float(BUSES[name]))
		AudioServer.set_bus_send(index, "Master")
		index += 1

	var layout := AudioServer.generate_bus_layout()
	var status := ResourceSaver.save(layout, OUT_PATH)
	if status != OK:
		push_error("could not write %s (error %d)" % [OUT_PATH, status])
		quit(1)
		return
	print("wrote %s with %d buses" % [OUT_PATH, AudioServer.bus_count])
	for i in AudioServer.bus_count:
		print("  %d %s %.1f dB" % [i, AudioServer.get_bus_name(i), AudioServer.get_bus_volume_db(i)])
	quit(0)
