#!/usr/bin/env python3
"""Regenerate prd.json from the milestone spec.

    python3 scripts/ralph/build_prd.py

`docs/MEADOWS_VERTICAL_SLICE.md` is authoritative (CLAUDE.md says so), so the
backlog is DERIVED from it rather than maintained beside it. Hand-editing
prd.json's story text would create a second spec, and the first thing the two
would disagree about is what "done" means.

One story per acceptance bullet, because that is already the granularity the
milestones use and it is the granularity the blind judge scores at.

Re-running preserves every `passes`, `evidence` and `review` value for stories
whose id still exists — so editing the spec adds and removes stories without
throwing away verdicts that were earned.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SPEC = ROOT / "docs" / "MEADOWS_VERTICAL_SLICE.md"
OUT = ROOT / "prd.json"

# M7 is geography, M11 is the creature cast, M15 is the polish gate. All three
# are "does this look right" questions, and the systems judge is the wrong
# instrument for them — it reads transcripts.
VISUAL = {"M7", "M11", "M15"}


def main() -> int:
    blocks = re.findall(
        r"^### (M\d+)\s*[—-]\s*(.+?)$\n(.*?)(?=^### |\Z)", SPEC.read_text(), re.S | re.M
    )
    if not blocks:
        print("no milestones found — has the spec's heading format changed?")
        return 1

    kept = {}
    if OUT.exists():
        for story in json.loads(OUT.read_text()).get("stories", []):
            kept[story["id"]] = story

    stories = []
    for milestone, title, body in blocks:
        for i, bullet in enumerate(re.findall(r"^-\s+(.+?)$", body, re.M), 1):
            sid = f"{milestone}-{i:02d}"
            was = kept.get(sid, {})
            stories.append(
                {
                    "id": sid,
                    "milestone": milestone,
                    "milestone_title": title.strip(),
                    "story": bullet.strip(),
                    "passes": bool(was.get("passes", False)),
                    "gate": "visual-judge" if milestone in VISUAL else "systems-judge",
                    "evidence": was.get("evidence", ""),
                    "review": was.get("review", ""),
                }
            )

    OUT.write_text(
        json.dumps(
            {
                "_comment": (
                    "GENERATED by scripts/ralph/build_prd.py from "
                    "docs/MEADOWS_VERTICAL_SLICE.md. Do not hand-edit the story "
                    "text; edit the spec and regenerate. `passes` is set ONLY by "
                    "a blind judge — see scripts/ralph/prompt.md. `passes: false` "
                    "means 'no blind judge has signed this off', which is not the "
                    "same as 'unimplemented': most of M0-M9 is built and ungated."
                ),
                "project": "Tetherbound — Meadows vertical slice",
                "stories": stories,
            },
            indent=2,
        )
        + "\n"
    )
    done = sum(1 for s in stories if s["passes"])
    print(f"{len(blocks)} milestones, {len(stories)} stories, {done} passing")
    return 0


if __name__ == "__main__":
    sys.exit(main())
